version: '3.8'

services:
  streamlit_app:
    build: .
    container_name: streamlit_container
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_RUN_ON_SAVE=true
